name: CICD-react

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker
        run: sudo docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/react_deploy .
      - name: Push Docker
        run: sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/react_deploy:latest
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.LIVE_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/react_deploy:latest

      - name: Copy React build files to running Nginx container
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.LIVE_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker cp /var/lib/docker/. nginxserver:/usr/share/nginx/html/
            sudo docker restart nginxserver
