name: CICD-react

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
          
      - name: List downloaded files1
        run: ls -l ./build

      - name: copy react build files to ec2
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu       
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.LIVE_SERVER_IP }}
          script_stop: true
          script: |
            sudo scp -r ./build/* ubuntu@${{ secrets.LIVE_SERVER_IP }}:/home/frontbuild/
