name: CICD-react

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu       
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.LIVE_SERVER_IP }}
          script_stop: true
          script: |
            sudo git clone https://github.com/BTC-LeeSoonMin/finalPjtSwimpyoFrontend.git
            sudo cp -r tmp/* home/frontbuild/
            sudo ls -al
            sudo rm -rf tmp
